language: cpp
dist: bionic
compiler: gcc
sudo: required # apt-get done in before_install.sh

# Only build master or PRs merging into master
branches:
  only:
  - master

# List of configurations to check
matrix:
  include:
      - os: linux
        env: FLIBCPP_DEV=ON GENERATOR=ninja
        addons:
          apt:
            packages:
            - python3-sphinx
            - valgrind
      - os: linux
        env: FLIBCPP_DEV=OFF GENERATOR=make
             FLIBCPP_FORTRAN_STD=f2003
             GCC_VERSION=8
      - os: linux
        env: FLIBCPP_DEV=OFF GENERATOR=make
             FLIBCPP_FORTRAN_STD=f2008
             GCC_VERSION=9
# Build phases
before_install:
  - source ./scripts/travis/before_install.sh
install:
  - ./scripts/travis/install.sh
script:
  - run_script configure
  - run_script compile
  - run_script test
  - run_script deploy
